# -*- coding: utf-8 -*-
"""Titanic_model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_1XykiWVTyFVZvNGdKMejxmAOh7BxA-Y

#Naive Bayes Algorithm

**p(a/b)=p(b/a)p(a)/p(b)**
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df=pd.read_csv('titanic.csv')
df.info()

df.drop(['PassengerId','Name','Cabin','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns',inplace=True)

df.info()

inputs=df.drop('Survived',axis=1)
target=df.Survived
inputs.head()

gendumy=pd.get_dummies(inputs.Sex)
gendumy.head()

inputs=pd.concat([inputs,gendumy],axis=1)

inputs.drop(['Sex'],axis=1,inplace=True)

inputs['Age'].fillna(inputs['Age'].median(),inplace=True)
inputs

inputs.isnull().sum()

inputs.columns[inputs.isna().any()]

inputs['Age'].hist()

inputs.drop_duplicates()

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(inputs,target,test_size=0.3)

from sklearn.naive_bayes import GaussianNB
model=GaussianNB()

model.fit(x_train,y_train)

model.predict(x_test[:10])

model.score(x_test,y_test)

model.predict([[2,19,30,0,1]])

"""##Deployment of model"""

import pickle

file="deployer.sav"

pickle.dump(model,open("deployer.sav",'wb'))

